version: '3'

services:

  media-app:
    image: media-image
    container_name: media-container
    build:
      dockerfile: Dockerfile
      context: ./

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

      - SPRING_RABBITMQ_HOST=rabbitmq-container

#      - spring_rabbitmq_port=5672
#      - spring_rabbitmq_username=guest
#      - spring_rabbitmq_password=guest

      - SPRING_REDIS_HOST=redis-container
      - SPRING_REDIS_PORT=6379

    ports:
      - 8086:8086
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

