version: '3'

services:

  rabbitmq:
    container_name: rabbitmq-container
    image: rabbitmq:3-management
    ports:
      - 4369:4369
      - 5672:5672
      - 25672:25672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  rabbitmq:
    driver: local
