version: '3'

services:

  redis:
    container_name: redis-container
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    entrypoint: redis-server --appendonly yes
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  redis-data:
    driver: local

